### ISSUE TITLE
Lackness of Info About Subscription

### ISSUE THREAD

**Issue by mesabuca** [iyzico/iyzipay-ruby#43]
There is some lackness on subscription params in [this document](https://dev.iyzipay.com/tr/subscription). There is no customer key or its definition for customer info but in [node js lib tests for subscription](https://github.com/iyzico/iyzipay-node/blob/a7dab36e7e46d6138ce513ef7015a9802576902f/samples/IyzipaySubscriptionSamples.js#L357) you used customer key. I think you should specify how should be params and put a test JSON params on documents.

**Comment by ShopskaSalad** [comment]
The issue has closed as there are no further updates.
